// packages/react-mfe/src/root.js
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';

import './index.css';
import App from './App';
import About from './components/About/About';

import { createMFEInstance, MFEController } from './controller';
window.log = window.log || (() => {});
const APP_ID = 'reactMFE1';

const instanceId = MFEController.getInstanceId();

window.log(`Loading module for ${instanceId}`);

export const rootConfig = {
  mount: async (container, appProps) => {
    const instanceId = appProps.instanceId;

    let root = null;
    if (!container) {
      console.info(`APP - ${APP_ID} container not found`);
      return;
    }

    createMFEInstance(appProps.instanceId, appProps);

    console.info(
      `MOUNTING: instance ${instanceId} of app group ${APP_ID}, `,
      container,
      appProps
    );

    root = ReactDOM.createRoot(container);
    root.render(
      <BrowserRouter basename={appProps.routerBasePath}>
        <App {...appProps} />
      </BrowserRouter>
    );

    return () => {
      console.info(`UNMOUNTING: instance ${instanceId} of app group ${APP_ID}`);
      root.unmount();
    };
  },

  xyzmount: async (container, appProps) => {
    console.info(
      `MOUNTING: xyz tree with instance ${appProps.instanceId} of app group ${APP_ID}, `,
      container,
      appProps
    );
    createMFEInstance(appProps.instanceId, appProps);
    const root = ReactDOM.createRoot(container);
    root.render(
      <BrowserRouter basename={appProps.routerBasePath}>
        <About {...appProps} />
      </BrowserRouter>
    );
    return () => {
      console.info(
        `UNMOUNTING: instance ${appProps.instanceId} of app group ${APP_ID}`
      );
      root.unmount();
    };
  },

  async get(params) {
    console.info('params', APP_ID, params);
    return params;
  },
};

MFEController.registerAppInstance(instanceId, rootConfig);

window.onload = () => {
  const appProps = MFEController.getMFEQueryParams();

  rootConfig.mount(document.getElementById('root'), {
    ...appProps,
    title: 'test',
    instanceId: instanceId ?? 'mfe1',
  });
};

// packages/stencil-mfe/root.ts
import { MFEController, createMFEInstance } from './src/controller';

(window as any).log = (window as any).log || (() => {});

const APP_ID = 'stencilMFE1';

const instanceId = MFEController.getInstanceId();

(window as any).log(`Loading module for ${instanceId}`);

const TYPE_ELEM_MAPPING = {
  'fw-sample1': { tag: 'fw-sample1' },
  'my-component': { tag: 'my-component' },
};

export const rootConfig = {
  mount: async (container, appProps) => {
    if (!container) {
      console.info(`APP - ${APP_ID} container not found`);
      return;
    }
    let webcmp = null;
    console.info(`MOUNT: ${APP_ID}`, container, appProps);

    // eslint-disable-next-line default-case

    const { tag } = TYPE_ELEM_MAPPING[appProps.componentType];
    webcmp = document.createElement(tag);
    webcmp.appProps = appProps;
    Object.keys(appProps).forEach((k) => {
      webcmp[k] = appProps[k];
    });

    // for stencil usecases , make sure the esm bundle is added to manifest. the below can be ignored
    // if (!(window as any).customElements.get(tag)) {
    //   customElements.define(tag, cmp);
    // }

    createMFEInstance(appProps.instanceId, webcmp);

    if (webcmp) container.appendChild(webcmp);

    return () => {
      console.info(`UNMOUNT: ${APP_ID} - Instance Id - ${appProps.instanceId}`);
      const { tag } = TYPE_ELEM_MAPPING[appProps.componentType];
      container.remove(tag);
    };
  },

  async get(params) {
    console.info('params', APP_ID, params);
    return params;
  },
};

MFEController.registerAppInstance(instanceId, rootConfig);

(window as any).onload = () => {
  const appProps = MFEController.getMFEQueryParams();
  rootConfig.mount(document.getElementById('stencilroot'), {
    title: 'test',
    ...appProps,
    componentType: 'fw-sample1',
    instanceId: instanceId || 'mfe5',
  });
};
